FROM php:8.1-alpine

RUN apk --update add wget \
  curl \
  git \
  build-base \
  libmcrypt-dev \
  libxml2-dev \
  pcre-dev \
  zlib-dev \
  autoconf \
  cyrus-sasl-dev \
  libgsasl-dev \
  oniguruma-dev \
  libressl \
  libressl-dev \
  supervisor


RUN pecl channel-update pecl.php.net; \
    docker-php-ext-install mbstring pdo tokenizer xml pcntl


RUN apk --update add postgresql-dev \
        && docker-php-ext-install pdo_pgsql

COPY docker/queue-consumer/supervisord.conf /etc/supervisord.conf
COPY docker/queue-consumer/supervisord.d/ /etc/supervisor/conf.d

ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]

# Clean up
RUN rm /var/cache/apk/* \
    && mkdir -p /var/www

COPY . /var/www

WORKDIR /etc/supervisor/conf.d/
